### ISSUE TITLE
Pretrained Weight Download

### ISSUE THREAD

**Issue by isangu** [youngwoo-yoon/Co-Speech_Gesture_Generation#1]
pretrained weight를 받을 수 있는 링크 https://www.dropbox.com/s/ijxjvot1o4s76ww/baseline_icra19_checkpoint_100.bin?dl=0 가

정상적이지 않은 것 같습니다. 404 not found 인 것 같은데 확인해주실 수 있으신가요?

**Comment by youngwoo-yoon** [comment]
알려주셔서 감사합니다. 방금 수정하였습니다.
