### ISSUE TITLE
TSV_FILE

### ISSUE THREAD

**Issue by chitianqilin** [youngwoo-yoon/Co-Speech_Gesture_Generation#10]
Where to get TSV files? or at least an example of TSV file containing transcripts?

**Comment by youngwoo-yoon** [comment]
If you're a GENEA challenge participant, you should be able to access TSV files. If you're not, please wait. We'll release the challenge dataset soon after the end of the challenge.

**Comment by zyhbili** [comment]
Wonderful work! When will the data be released? It will be helpful for further research. @youngwoo-yoon

**Comment by youngwoo-yoon** [comment]
Hello @chitianqilin and @zyhbili,
We've released the 2022 challenge dataset including TSV files. Please visit https://youngwoo-yoon.github.io/GENEAchallenge2022/
This is the direct link to the dataset: https://doi.org/10.5281/zenodo.6998230
