### ISSUE TITLE
pymo 'to position' for Trinity 

### ISSUE THREAD

**Issue by YoungSeng** [youngwoo-yoon/Co-Speech_Gesture_Generation#13]
Hello, for Trinity dataset, in GENEA challenge 2020, is the `_to_pos` function in its `preprocessing.py` in `pymo` not working, because I can't get it to work successfully using `('param', MocapParameterizer('position'))` in the `pipeline`.

How can this be solved? Thanks!

**Comment by youngwoo-yoon** [comment]
Hello, 
please try GENEA_2020 tagged version (https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/tree/GENEA_2020) if you're currently using the latest version.
PyMo has dependencies on the joint configuration, so the code is slightly modified for the GENEA 2022 dataset.

**Comment by YoungSeng** [comment]
Yes, I was using this branch and was strange not to work.

**Comment by TeoNikolov** [comment]
I am linking information from this comment https://github.com/genea-workshop/Speech_driven_gesture_generation_with_autoencoder/issues/2#issuecomment-1229198521

> Okay, thank you, I uploaded my code [here](https://github.com/YoungSeng/Pymo-Issue). For the TestSeq001.bvh file in the GENEA validation set, there are 71 joints in the whole body, minus 14 joints with Nub, leaving 57 joints, the coordinates of its position should be 171, but only 162 after conversion, what should I do?

---

Note that I cannot help much with this issue right now, as I have not used the GENEA 2020 dataset, and it would take me a while to get things running to try and reproduce the issue on my computer.

**Comment by youngwoo-yoon** [comment]
Hello,
Sorry for the late reply.
I just ran your test script and I found that it gives 171 values, which is the expected number, if you do not use `ConstantsRemover` at line 51 in `bvh_to_position.py`.

**Comment by YoungSeng** [comment]
Thank you for your reply, I'll try again, thank you so much.

**Comment by YoungSeng** [comment]
I commented out the line and it was 225 instead of 171, which is strange. @youngwoo-yoon

**Comment by youngwoo-yoon** [comment]
I used the code and bvh file in https://github.com/YoungSeng/Pymo-Issue. And I got the output numpy matrix in (2577, 171) shape. The processing pipeline is as follows.
```
    data_pipe = Pipeline([
        ('dwnsampl', DownSampler(tgt_fps=20, keep_all=False)),
        ('root', RootTransformer('hip_centric')),
        ('param', MocapParameterizer('position')),        # expmap, position
        ('np', Numpyfier())
    ])
```

**Comment by YoungSeng** [comment]
Thanks for the answer, but strangely enough that's what I did, but couldn't get the correct result. 

In any case, I got 171 with another approach, which was to set at the beginning:

```
target_joints = ['Hips', 'LeftUpLeg', 'LeftLeg', 'LeftFoot', 'LeftForeFoot', 'LeftToeBase', 'RightUpLeg', 'RightLeg', 'RightFoot', 'RightForeFoot', 'RightToeBase', 'Spine', 'Spine1', 'Spine2', 'Spine3', 'pCube4', 'LeftShoulder', 'LeftArm', 'LeftForeArm', 'LeftHand', 'LeftHandPinky1', 'LeftHandPinky2', 'LeftHandPinky3', 'LeftHandRing1', 'LeftHandRing2', 'LeftHandRing3', 'LeftHandMiddle1', 'LeftHandMiddle2', 'LeftHandMiddle3', 'LeftHandIndex1', 'LeftHandIndex2', 'LeftHandIndex3', 'LeftHandThumb1', 'LeftHandThumb2', 'LeftHandThumb3', 'RightShoulder', 'RightArm', 'RightForeArm', 'RightHand', 'RightHandPinky1', 'RightHandPinky2', 'RightHandPinky3', 'RightHandRing1', 'RightHandRing2', 'RightHandRing3', 'RightHandMiddle1', 'RightHandMiddle2', 'RightHandMiddle3', 'RightHandIndex1', 'RightHandIndex2', 'RightHandIndex3', 'RightHandThumb1', 'RightHandThumb2', 'RightHandThumb3', 'Neck', 'Neck1', 'Head']

```

Then the pipeline is:

```
    data_pipe = Pipeline([
        ('dwnsampl', DownSampler(tgt_fps=60, keep_all=False)),
        ('root', RootTransformer('hip_centric')),
        ('jtsel', JointSelector(target_joints, include_root=False)),     # (225) -> 171
        ('pos', MocapParameterizer('position')),
        ('np', Numpyfier())
    ])
```

Anyway the problem can be solved, thank you!
