### ISSUE TITLE
trinity_data_to_lmdb 관련 질문입니다.

### ISSUE THREAD

**Issue by isangu** [youngwoo-yoon/Co-Speech_Gesture_Generation#2]
Trinity Dataset을 신청하여 받은 데이터셋은 .fbx 파일과 .wav 파일인 것 같은데,

 trinity_data_to_lmdb.py 에서는 .bvh의 모션파일과 .json의 subtitle이 필요한 듯 보입니다.

1) 혹시 fbx파일을 bvh로 변환하여 사용하여하 하나요?

2) json파일은 어디서 구할 수 있는지 알 수 있을까요?

이상입니다.

**Comment by youngwoo-yoon** [comment]
네 맞습니다. 지금 진행하고 있는 GENEA Compeition 용으로 변환 및 전처리된 데이터가 필요합니다. https://genea-workshop.github.io/2020/#gesture-generation-challenge
현재는 참가자들에게만 데이터를 제공하였습니다. Competition 이 끝난 후에 데이터를 공개할 예정이므로 조금 기다려주시기 바랍니다.

**Comment by isangu** [comment]
네 답변 감사드립니다.
