### ISSUE TITLE
Why do 15 joints of one sample has shape [30,135]?

### ISSUE THREAD

**Issue by chuangyu-robotics** [youngwoo-yoon/Co-Speech_Gesture_Generation#3]
in the file: ../Co-Speech_Gesture_Generation/blob/master/scripts/data_loader/lmdb_data_loader.py
i run the line 69:   word_seq, pose_seq, audio, aux_info = sample

I got the pose_seq has the shape [30,135]. i know 30 is the frame size of each example. and 135  is for 15 selected joints. as 135/15=9, namely each joint has 9 values. what do those 9 values mean resepctively?  

Thank you in advance.

**Comment by youngwoo-yoon** [comment]
Nine values in a 3x3 rotation matrix. Please see `process_bvh` function in `trinity_data_to_lmdb.py`.
The original paper used Cartesian coordinates of upper-body joints, but I changed to use rotation matrices since rotational angles were required in the GENEA competition.

**Comment by chuangyu-robotics** [comment]
I got it. Thanks a lot.
