### ISSUE TITLE
No audio input

### ISSUE THREAD

**Issue by birdflies** [youngwoo-yoon/Co-Speech_Gesture_Generation#7]
Dear, 
This project only support text input. It seems that you did not use audio data~ 
```
 in_text = in_text.to(device)
 in_audio = in_audio.to(device)
 target_vec = target_vec.to(device)
 loss = train_iter_seq2seq(args, epoch, in_text, text_lengths, target_vec, generator, gen_optimizer)
```

**Comment by youngwoo-yoon** [comment]
You're right. This project do not use audio data so `in_audio` is never used. If you're interested in using text+audio data, please see our follow-up project https://github.com/ai4r/Gesture-Generation-from-Trimodal-Context.

**Comment by birdflies** [comment]
Thanks, do [Gesture-Generation-from-Trimodal-Context](https://github.com/ai4r/Gesture-Generation-from-Trimodal-Context)  support the input format of Trinity Speech-Gesture Dataset for GENEA Challenge 2020?

**Comment by youngwoo-yoon** [comment]
No, it doesn't. You have to modify the code to make it compatible with the GENEA challenge dataset.
