### ISSUE TITLE
Visualization BVH

### ISSUE THREAD

**Issue by YoungSeng** [youngwoo-yoon/Co-Speech_Gesture_Generation#9]
Hello. After inference step, we can get the .bvh. 

Is there any way or code to visualize it and get the effect same as the paper?

I find [this](https://github.com/jonepatr/genea_visualizer), but I do not have the user and password

**Comment by youngwoo-yoon** [comment]
Our papers didn't use BVH format, so the Blender script we used is not compatible to BVH outputs.
I noticed your're GENEA 2022 Challenge participant. If it is right, the 3D character visualization tool will be available soon.

**Comment by YoungSeng** [comment]
Thanks, and I can use [blender](https://www.blender.org/download/) in windows to visualize the BVH.

So nice of you~

**Comment by Svito-zar** [comment]
And the GENEA 2022 Visualizer is also available now: 
https://github.com/TeoNikolov/genea_visualizer

**Comment by YoungSeng** [comment]
Yeah, I got! Thank you very much
